#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 openwrt-system-monitor
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
START=99
STOP=15
NAME=sysmonitor
APP_PATH=/usr/share/$NAME

stop()
{
	set sysmonitor.sysmonitor.enable=0
	set commit sysmonitor
}
start()
{
	if [ -f "/etc/init.d/ddns" ]; then
		[ $(ps -w|grep ddns|grep -v grep|wc -l) == 0 ] && /etc/init.d/ddns restart &
	fi
	set sysmonitor.sysmonitor.enable=1
	set commit sysmonitor
	$APP_PATH/sysapp.sh minidlna
	$APP_PATH/sysapp.sh lighttpd
	$APP_PATH/sysapp.sh samba
	$APP_PATH/sysmonitor.sh &
}


